// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obkezbshzvtqmvgbxsth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ia2V6YnNoenZ0cW12Z2J4c3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNjI5ODMsImV4cCI6MjA1NTczODk4M30.0fBD-JPPgUV2DU4_7S1vKFvIer602mYwAe5EIxiLp0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);